apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# - service.yml
resources:
- deployment.yml
- service.yml

namespace: clone-linkdln

images:
- name: clone-linkedln
  newName: marcosaureliofarias/clone-linkedln
  newTag: 5e5646a65fd51073cccb2dd3c531f1591d674c54
