apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

namespace: clone-linkdln

images:
- name: clone-linkedln
  newName: marcosaureliofarias/clone-linkedln
  newTag: b97525d5efa06548859c8dd266c2341b3b043696
